### ISSUE TITLE
identifying the functional SNP

### ISSUE THREAD

**Issue by xasancakjnc** [Xinglab/PAIRADISE#12]
Hi,
I have performed the PAIRADISE analysis in our own data, and we detected some significant SNP-splicing event pairs, there are two questions that confused me:

1. Can I directly treated these SNPs as fuctional SNP?
2. The number of the pairs were limited, I guess it may be attributed to restricting the candidate(heterozygous) SNPs to the flanking constitutive exons region. As far as I know, the SNPs within the alternative exon can also affect the alternative splicing, is there any solution to include these SNPs as well?

Thank you.

**Comment by EricKutschera** [comment]
Levon developed PAIRADISE. I don't think he'll see this github issue, but you could try https://github.com/Xinglab/PAIRADISE#contact to ask him for more details.

These seem to be the relevant lines from the paper: https://doi.org/10.1016/j.ajhg.2020.07.005

> We envision many of the identified SNPs as tagging (i.e., in very strong LD with) the causal SNPs that affect splicing regulation, while the causal SNPs could be located within the alternative exons or nearby intronic regions and are not tested by PAIRADISE.

> All SNPs within the alternatively spliced exon are excluded in the subsequent PAIRADISE analysis because these SNPs can only be detected from the exon inclusion isoform. Although the haplotype information is used in RNA-seq read mapping to obtain haplotype-specific reads, in downstream analyses we associate AS events with individual SNPs and match AS event-SNP pairs across people based on each SNP separately. This is done to avoid the complication that there could be more than two haplotypes across a set of SNPs within a population so haplotypes cannot be matched across people.
