### ISSUE TITLE
Why number of cores limited to 8 ?

### ISSUE THREAD

**Issue by gouthamatla** [Xinglab/PAIRADISE#2]
Hi,

I am just curious why there is a limit of 8 cores in foreach function. I have access to cluster that have nodes with 40 cores, I am wondering if I could use more cores than 8.

https://github.com/Xinglab/PAIRADISE/blob/105b168faeed6597e8070b1335801b51c83d89fb/pairadise/src/pairadise_model/R/pairadise.R#L83-L84

Thanks,
Goutham A

**Comment by LevonDem** [comment]
Thank you for the question. You're correct - we will remove this restriction shortly.

**Comment by gouthamatla** [comment]
So that means I can use more cores ?
