### ISSUE TITLE
Could you please provide an example of the RNA edit file?

### ISSUE THREAD

**Issue by xasancakjnc** [Xinglab/PAIRADISE#8]
Due to some reason, the file containing RNA edit information cannot be downloaded from RADAR. Could you please tell me what is the data form of this txt, which will make it available for us to use the RNA edit file downloaded from other websites, such as the Rediportal. Or it would be appreciated if you put this RADAR file into github.

Thank you.

**Comment by EricKutschera** [comment]
That file was uploaded to a separate branch of this repo. I just merged that branch and the file is available at: https://github.com/Xinglab/PAIRADISE/blob/master/Human_AG_all_hg19_v2.txt.gz
